openapi: 3.2.0
$self: https://example.com/oad/parameters
info:
  title: Shared Parameters
  version: 1.0.0
components:
  parameters:
    OrderId:
      name: orderId
      in: path
      required: true
      schema:
        $ref: './schemas#/components/schemas/OrderId'
